### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/skywater130#8]
https://github.com/gdsfactory/gdsfactory/issues/176

# TODO

- [ ] make PCells (see below)
- [ ] add pyspice demos fir models and simulations
- [ ] add notebooks with documentation
- [ ] LVS. In LVS, the software will extract the fundamental components (e.g. diodes, transistors) based on the layout and compare it to the netlist
- [ ]  QRC extraction, or more accurately, RLCK parasitic elements. This is essential for RF circuits, otherwise, the simulation results are useless.
- [ ] Customize main parametric components such as transistors, capacitors, diodes resistors, etc. Remember, those ready-made blocks you show in your video from Skywater are not very useful in this context as they are for automatic digital place and route. Once this is completed, a spice-compatible netlist is generated, and we can use ngspice and [EEsim](https://github.com/danchitnis/EEsim) to display results etc.

# Pcells to make

- [x] NMOS
- [ ] transistors
- [ ] capacitors
- [ ] diodes
- [ ] resistors

# Maybe

- [ ] openroad plugin. Invoke Yosis from gdsfactory

@proppy
@mithro
@danchitnis
@skandanc

**Comment by daquintero** [comment]
I'd be happy to help integrate a GDSFactory/OpenRoad plugin as I already have something similar I hope to be releasing soon!

**Comment by joamatab** [comment]
nice Dario,

we have also been thinking about integrating with [vlsir](https://github.com/Vlsir)

@growly
@dan-fritchman

**Comment by tcaduser** [comment]
Is there any need for open source capacitance extraction?

**Comment by daquintero** [comment]
I've seen some really cool work in gplugins re Elmer capacitance extraction open source. I guess a demo on this Skywater 130nm pdk would be really cool for analogue/RF design!

**Comment by mithro** [comment]
There is gds2para - https://github.com/purdue-onchip/gds2Para

**Comment by joamatab** [comment]
https://gdsfactory.github.io/gplugins/notebooks/elmer_01_electrostatic.html

@nikosavola

**Comment by tcaduser** [comment]
Thanks.  The Elmer thing is something I was going to offer to be done using DEVSIM.  However, it looks like Elmer is already doing it!

**Comment by joamatab** [comment]
a DEVSIM alternative tutorial would be great, as it's easier to install

PRs mostly welcome for this

**Comment by nikosavola** [comment]
The same capacitive simulation can also be done in Palace, which might be easier to set up, see https://gdsfactory.github.io/gplugins/notebooks/palace_01_electrostatic.html

**Comment by tcaduser** [comment]
> a DEVSIM alternative tutorial would be great, as it's easier to install
> 
> PRs mostly welcome for this

thanks, I'll look into it
